apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-config
  namespace: cam2
data:
  Corefile: |
    .:53 {
      errors
      health
      hosts {
        10.11.77.251 api.ustream.tv
        fallthrough
      }
      ready
      forward . 192.168.16.5
      loop
      reload
      loadbalance
    }
