apiVersion: v1
kind: Service
metadata:
  name: cam1-nginx-service
  labels:
    app: cam1-sonycam-nginx
  namespace: cam1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cam1.svc.technotut.net
spec:
  selector:
    app: cam1-sonycam-nginx
  type: LoadBalancer
  loadBalancerIP: 10.11.77.252
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
